steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$total-vertex-401719/kaur-Repo:$COMMIT_SHA', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$total-vertex-401719/kaur-Repo:$COMMIT_SHA']

# setup cloud sdk

images:
  - gcr.io/$total-vertex-401719/kaur-Repo:$COMMIT_SHA

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET


